name = "apuu"
uuid = "633394ee-c017-41e2-b666-f3fce985accc"
version = "0.1.0"
authors = ["JonathanSomer <jonathan.somer@protonmail.com>"]

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"

[compat]
Distributions = "0.25.122"
LinearAlgebra = "1.12.0"
Parameters = "0.12.3"
Plots = "1.41.1"
Random = "1.11.0"
Revise = "3.12.2"
StatsBase = "0.34.8"
StatsPlots = "0.15.8"
